import type { IconType } from "react-icons";
import {
  BiLogoReact,
  BiLogoJavascript,
  BiLogoPython,
  BiLogoJava,
  BiLogoTypescript,
  BiLogoNodejs,
  BiLogoGoLang,
  BiLogoCPlusPlus,
  BiLogoPhp,
  BiLogoPostgresql,
  BiLogoMongodb,
  BiLogoAngular,
  BiLogoVuejs,
  BiLogoDocker,
} from "react-icons/bi";
import {
  SiRust,
  SiKubernetes,
  SiSwift,
  SiKotlin,
  SiRuby,
  SiGraphql,
  SiRedis,
  SiNextdotjs,
  SiGit,
} from "react-icons/si";
import { FaNetworkWired, FaAws, FaLinux, FaHtml5, FaCogs } from "react-icons/fa";
import { TbBrandCSharp } from "react-icons/tb";

export const techIconMap: Record<string, IconType> = {
  react: BiLogoReact,
  javascript: BiLogoJavascript,
  python: BiLogoPython,
  java: BiLogoJava,
  typescript: BiLogoTypescript,
  nodejs: BiLogoNodejs,
  go: BiLogoGoLang,
  cpp: BiLogoCPlusPlus,
  php: BiLogoPhp,
  sql: BiLogoPostgresql,
  rust: SiRust,
  "system-design": FaNetworkWired,
  csharp: TbBrandCSharp,
  docker: BiLogoDocker,
  kubernetes: SiKubernetes,
  aws: FaAws,
  angular: BiLogoAngular,
  vuejs: BiLogoVuejs,
  swift: SiSwift,
  kotlin: SiKotlin,
  ruby: SiRuby,
  mongodb: BiLogoMongodb,
  graphql: SiGraphql,
  linux: FaLinux,
  git: SiGit,
  "html-css": FaHtml5,
  nextjs: SiNextdotjs,
  redis: SiRedis,
  devops: FaCogs,
};
